USE [master]
GO
CREATE DATABASE [AirBnBSanFrancisco2]
 CONTAINMENT = NONE
GO
ALTER DATABASE [AirBnBSanFrancisco] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AirBnBSanFrancisco].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AirBnBSanFrancisco] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET ARITHABORT OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET  MULTI_USER 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AirBnBSanFrancisco] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AirBnBSanFrancisco] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'AirBnBSanFrancisco', N'ON'
GO
ALTER DATABASE [AirBnBSanFrancisco] SET QUERY_STORE = OFF
GO